# generated by Git for Windows

# WARNING: Do NOT edit this config file in ~/. Make sure you are editing the
# source file at ~/home_repo/home_dir and run bin/refreshHomeFromRepo to update.

test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
